

import { Language, RoadmapStep, UserType, Bank, Alert, SmartAssistantResult } from './types';

export const INITIAL_ROADMAP: RoadmapStep[] = [
  {
    id: 'esim',
    title: 'Get Connected',
    description: 'Activate your French mobile number (eSIM).',
    status: 'current',
    day: 'Day 1',
    iconName: 'smartphone'
  },
  {
    id: 'bank',
    title: 'Open Bank Account',
    description: 'Get your RIB (Bank Identity Statement).',
    status: 'locked',
    day: 'Day 2',
    iconName: 'credit-card'
  },
  {
    id: 'navigo',
    title: 'Transport Pass',
    description: 'Get your Navigo card for Paris transport.',
    status: 'locked',
    day: 'Week 3',
    iconName: 'train'
  },
  {
    id: 'caf',
    title: 'Apply for CAF',
    description: 'Housing allowance application.',
    status: 'locked',
    day: 'Day 5',
    iconName: 'home'
  },
  {
    id: 'ameli',
    title: 'Health Insurance',
    description: 'Register for Ameli (Social Security).',
    status: 'locked',
    day: 'Week 2',
    iconName: 'heart-pulse'
  }
];

// Changed to keys for translation lookup
export const REQUIRED_DOCUMENTS: Record<UserType, string[]> = {
  [UserType.STUDENT]: ['passport', 'visa', 'address_proof', 'school_certificate'],
  [UserType.WORKER]: ['passport', 'visa', 'address_proof', 'work_contract'],
  [UserType.VISITOR]: ['passport', 'visa', 'address_proof']
};

export const FRENCH_BANKS: Bank[] = [
  // Online
  { id: 'n26', name: 'N26', category: 'online', logoColor: 'bg-teal-500', url: 'https://n26.com', features: ['Instant IBAN', 'No fees'] },
  { id: 'bourso', name: 'Boursorama', category: 'online', logoColor: 'bg-pink-600', url: 'https://boursorama.com', features: ['Welcome Bonus', 'Low fees'] },
  { id: 'revolut', name: 'Revolut', category: 'online', logoColor: 'bg-blue-500', url: 'https://revolut.com', features: ['Multi-currency', 'Fast app'] },
  { id: 'fortuneo', name: 'Fortuneo', category: 'online', logoColor: 'bg-green-600', url: 'https://fortuneo.fr', features: ['Free Gold Card', 'French IBAN'] },
  
  // Physical
  { id: 'bnp', name: 'BNP Paribas', category: 'physical', logoColor: 'bg-green-700', url: 'https://mabanque.bnpparibas', hasOnlineBooking: true, address: '12 Av. de l\'Opéra, Paris', phone: '01 42 98 10 10', features: ['Large network', 'Student offers'] },
  { id: 'lcl', name: 'LCL', category: 'physical', logoColor: 'bg-blue-700', url: 'https://lcl.fr', hasOnlineBooking: true, address: '4 Place de l\'Opéra, Paris', phone: '09 69 36 30 30', features: ['Good for workers', 'Insurance'] },
  { id: 'sg', name: 'Société Générale', category: 'physical', logoColor: 'bg-red-600', url: 'https://particuliers.sg.fr', hasOnlineBooking: false, address: '29 Bd Haussmann, Paris', phone: '01 44 86 60 00', features: ['International', 'Classic'] },
  { id: 'cic', name: 'CIC', category: 'physical', logoColor: 'bg-blue-800', url: 'https://cic.fr', hasOnlineBooking: false, address: '15 Rue de la Paix, Paris', phone: '08 00 00 60 60', features: ['Regional', 'Personal advisor'] },
];

// Helper for type-safe translations including arrays
export interface TranslationData {
    [key: string]: any;
    faqs: {q: string, a: string}[];
    help_links: {name: string, url: string, icon: string}[];
    alerts: Alert[];
    // New nested structures
    docs: { [key: string]: string };
    cta: { [key: string]: string };
    identity_labels: { [key: string]: string };
    bank_reasons: { [key: string]: string };
    mock_ai: {
        administrative: SmartAssistantResult;
        safety: SmartAssistantResult;
    };
}

export const TRANSLATIONS: Record<Language, TranslationData> = {
  [Language.EN]: {
    welcome: "Welcome to France",
    subtitle: "Your 48-hour rapid settlement guide.",
    start_journey: "Start Journey",
    upload_doc: "Upload Document",
    analyzing: "AI Analyzing...",
    dashboard: "Dashboard",
    esim: "eSIM",
    banking: "Banking",
    assistant: "Assistant", 
    profile: "Profile",
    actions: "Action Items",
    translate: "Translate",
    // Docs & CTA
    docs: {
      passport: "Passport",
      visa: "Visa",
      address_proof: "Proof of Address",
      school_certificate: "School Certificate",
      work_contract: "Work Contract"
    },
    cta: {
      upload_single: "Upload",
      upload_all: "Upload all files at once",
      analyze: "AI Analyze & Recommend",
      reupload: "Re-upload"
    },
    identity_labels: {
      student: "Student",
      worker: "Worker",
      visitor: "Visitor"
    },
    bank_reasons: {
        student_online: "Best for Students: No income proof needed.",
        student_bnp: "Strong student partnerships & campus presence.",
        worker_physical: "Ideal for salary deposits & full insurance.",
        worker_lcl: "Great for workers & mortgages.",
        visitor_online: "Fastest opening for visitors.",
        visitor_physical: "Harder to open without long-stay visa.",
        default: "Good standard option."
    },
    // Banking New Flow
    bk_already_have: "Already have a bank account?",
    bk_enter_iban: "Enter IBAN or RIB",
    bk_iban_placeholder: "FR76 1234 5678...",
    bk_confirm_iban: "Confirm Account",
    bk_account_added: "Bank Account Added!",
    bk_add_card_intro: "Continue to add a card for management & payments:",
    bk_add_card_title: "Add Bank Card (NFC/Manual)",
    bk_add_nfc: "Add via NFC",
    bk_add_manual: "Manual Input",
    bk_nfc_instruction: "Hold card to the back of your phone",
    bk_nfc_scanning: "Scanning...",
    bk_card_added: "Card added successfully",
    bk_my_cards: "My Cards",
    bk_manual_card_num: "Card Number",
    bk_manual_expiry: "Expiry (MM/YY)",
    bk_add_card_btn: "Add Card",
    bk_manual_upload: "Upload Card Photo (Optional)",
    // Dashboard Specific
    dash_hello: "Hello",
    dash_stage_title: "Current Stage",
    dash_day_label: "Day",
    dash_tasks_left: "tasks remaining",
    dash_completed_pre: "You have completed",
    dash_completed_post: "tasks",
    dash_next_action: "Next Action",
    dash_start_btn: "Start",
    dash_alerts: "Alerts",
    dash_quick_actions: "Quick Actions",
    qa_num: "French Number",
    qa_bank: "Bank",
    qa_navigo: "Navigo",
    qa_caf: "CAF",
    qa_ameli: "Ameli",
    qa_ai: "Smart AI",
    // Smart Assistant
    sa_title: "Smart Assistant",
    sa_subtitle: "Administrative & Safety AI",
    sa_mode_admin: "Admin Analysis",
    sa_mode_admin_desc: "Analyze letters, emails & documents",
    sa_mode_safety: "Safety Check",
    sa_mode_safety_desc: "Check suspicious SMS, URLs or Emails",
    sa_input_placeholder: "Paste text, URL or upload image...",
    sa_analyze_btn: "Analyze Now",
    sa_risk_high: "HIGH RISK",
    sa_risk_medium: "MEDIUM RISK",
    sa_risk_low: "SAFE",
    sa_safe_link: "Official Safe Link",
    sa_deadline: "Deadline",
    sa_history: "Recent Analysis",
    sa_section_analysis: "Analysis",
    sa_section_advice: "Action Advice",
    sa_btn_another: "Analyze Another",
    sa_demo_btn: "Demo",
    sa_doc_summary: "Document Summary",
    // Onboarding
    ob_step2_title: "Orange Global Life",
    ob_step2_desc: "The ultimate administrative companion for your first 90 days in France.",
    ob_feat_esim: "French Number",
    ob_feat_bank: "Bank & RIB",
    ob_feat_navigo: "Transport",
    ob_feat_caf: "Health & Housing",
    ob_step3_title: "Your First 90 Days",
    ob_day1: "Day 1",
    ob_day3: "Day 1-3",
    ob_week1: "Week 1",
    ob_week2: "Week 2",
    btn_continue: "Continue",
    btn_start: "Start My Journey",
    // Profile
    p_identity: "Identity",
    p_name_label: "Name",
    p_guest: "Guest User",
    p_type: "User Type",
    p_student: "Student",
    p_worker: "Worker",
    p_visitor: "Visitor",
    p_prefs: "Preferences",
    p_lang: "Language",
    p_notifs: "Notifications",
    p_docs: "My Documents",
    p_doc_added: "Added Day 1",
    p_doc_missing: "Missing",
    p_empty_docs: "No documents uploaded yet.",
    p_export: "Export Administrative Package",
    p_downloading_alert: "Administrative Package (ZIP) downloaded!",
    p_privacy: "Privacy & Data",
    p_help: "Help Center",
    p_reset: "Reset Demo",
    p_phone: "Phone Number",
    p_userid: "User ID",
    p_delete: "Delete Account",
    p_delete_confirm: "Are you sure? This will wipe all data.",
    // Banking
    bk_identity_title: "Who are you?",
    bk_identity_desc: "We need your profile to recommend the best bank.",
    bk_step1_title: "Documents",
    bk_step1_desc: "Required for your profile:",
    bk_upload_tip: "AI Auto-Classification Active",
    bk_upload_pkg: "Analyze My Documents",
    bk_analyzing: "AI Scoring Banks...",
    bk_stat_compat: "Compatibility",
    bk_stat_success: "Success Rate",
    bk_rec_title: "Recommended Banks",
    bk_rec_online: "Online Banks",
    bk_rec_physical: "Agencies",
    bk_open: "Open Website",
    bk_book: "Book Appointment",
    bk_call: "Call Agency",
    bk_score: "Score",
    bk_filter_all: "All",
    bk_filter_online: "Online",
    bk_filter_physical: "Agencies",
    // eSIM
    esim_start: "Start eSIM Activation",
    esim_checking: "Checking device compatibility...",
    esim_compatible: "Your device is compatible with eSIM.",
    esim_incompatible: "Your device does not support eSIM.",
    esim_passport_label: "Passport Number",
    esim_activate: "Activate Now",
    esim_activating: "Activating Profile...",
    esim_connecting: "Connecting to Orange France Towers...",
    esim_store_opt: "Go to nearest Orange Store",
    esim_kiosk_opt: "Get SIM at Airport Kiosk",
    esim_skip: "Skip for now",
    esim_success: "eSIM Activated Successfully",
    esim_success_desc: "Your French number is ready:",
    esim_continue: "Continue",
    esim_already_have: "Already have a SIM?",
    esim_track_usage: "Track Usage",
    esim_enter_number: "Enter your French Number",
    esim_plan_usage: "Plan Usage",
    esim_data_left: "Data Remaining",
    esim_unlimited: "Unlimited",
    esim_calls_sms: "Calls & SMS",
    esim_days_left: "Days Remaining",
    esim_balance: "Balance",
    esim_renew: "Renews on",
    esim_redownload: "eSIM Redownload",
    esim_redownload_available: "Available",
    esim_btn_history: "History",
    esim_btn_topup: "Top Up",
    esim_btn_plan: "Change Plan",
    esim_account_created: "Account Created to save progress.",
    // Help Center
    help_title: "Help Center",
    help_official_links: "Official Resources",
    help_faq: "Frequently Asked Questions",
    help_safety_title: "Stay Safe",
    help_safety_desc: "Never share your passwords or banking PINs via SMS. Official agencies (CAF, Ameli) will never ask for them by text message.",
    splash_loading: "Loading your French journey...",
    
    // Arrays
    faqs: [
        { q: "How do I get a Social Security Number?", a: "Register on etudiant-etranger.ameli.fr immediately after arrival." },
        { q: "Can I open a bank account without a French number?", a: "Some online banks (N26, Revolut) allow it, but traditional banks require one." },
        { q: "What is a RIB?", a: "Relevé d'Identité Bancaire. It's your bank details required for salary and direct debits." },
    ],
    help_links: [
        { name: 'CAF (Family Allowance)', url: 'https://www.caf.fr', icon: '🏠' },
        { name: 'Ameli (Health Insurance)', url: 'https://www.ameli.fr', icon: '❤️' },
        { name: 'Navigo (Transport)', url: 'https://www.iledefrance-mobilites.fr', icon: '🚇' },
        { name: 'Service Public (Admin)', url: 'https://www.service-public.fr', icon: '🇫🇷' },
    ],
    alerts: [
      {
        id: '1',
        type: 'administrative',
        title: 'CAF : Document manquant',
        description: 'Please upload your rental contract.',
        date: '12 Déc',
        actionLabel: 'Upload'
      },
      {
        id: '2',
        type: 'security',
        title: 'Attention : message suspect',
        description: 'Suspicious SMS detected. Do not click links.',
        actionLabel: 'Check'
      }
    ],
    mock_ai: {
      administrative: {
        type: 'administrative',
        summary: "CAF requires a missing document (Rental Contract) to proceed with your housing aid application.",
        steps: [
          "Scan your 'Bail de location' (Rental Contract).",
          "Log in to caf.fr > My Profile.",
          "Upload the document in 'Mes Démarches'."
        ],
        deadline: "2024-10-05",
        official_links: [{ name: "CAF - Mon Compte", url: "https://www.caf.fr" }]
      },
      safety: {
        type: 'safety',
        risk_level: 'high',
        explanation: "This is a common 'Phishing' attempt. The URL 'ameli-renouvellement.com' is FAKE. The official site is ameli.fr.",
        advice: "Do NOT click the link. Block the sender. Delete the message.",
        official_link: { name: "Ameli Official", url: "https://www.ameli.fr" }
      }
    }
  },
  [Language.FR]: {
    welcome: "Bienvenue en France",
    subtitle: "Votre guide d'installation rapide en 48h.",
    start_journey: "Commencer",
    upload_doc: "Télécharger",
    analyzing: "Analyse IA...",
    dashboard: "Tableau de bord",
    esim: "eSIM",
    banking: "Banque",
    assistant: "Assistant",
    profile: "Profil",
    actions: "Actions requises",
    translate: "Traduire",
    docs: {
      passport: "Passeport",
      visa: "Visa",
      address_proof: "Justificatif de domicile",
      school_certificate: "Certificat de scolarité",
      work_contract: "Contrat de travail"
    },
    cta: {
      upload_single: "Télécharger",
      upload_all: "Tout télécharger",
      analyze: "Analyser et Recommander",
      reupload: "Changer"
    },
    identity_labels: {
      student: "Étudiant",
      worker: "Travailleur",
      visitor: "Visiteur"
    },
    bank_reasons: {
        student_online: "Idéal pour étudiants : Aucun revenu exigé.",
        student_bnp: "Partenariats étudiants & présence campus.",
        worker_physical: "Idéal pour domiciliation salaire & assurances.",
        worker_lcl: "Excellent pour travailleurs & prêts immo.",
        visitor_online: "Ouverture la plus rapide pour visiteurs.",
        visitor_physical: "Difficile sans visa long séjour.",
        default: "Bonne option standard."
    },
    // Banking New Flow
    bk_already_have: "Déjà un compte bancaire ?",
    bk_enter_iban: "Entrez IBAN ou RIB",
    bk_iban_placeholder: "FR76 1234 5678...",
    bk_confirm_iban: "Confirmer",
    bk_account_added: "Compte bancaire ajouté !",
    bk_add_card_intro: "Continuez à ajouter une carte pour la gestion & les paiements :",
    bk_add_card_title: "Ajouter une carte (NFC/Manuel)",
    bk_add_nfc: "Via NFC",
    bk_add_manual: "Entrée Manuelle",
    bk_nfc_instruction: "Approchez la carte du dos du téléphone",
    bk_nfc_scanning: "Scan en cours...",
    bk_card_added: "Carte ajoutée avec succès",
    bk_my_cards: "Mes Cartes",
    bk_manual_card_num: "Numéro de carte",
    bk_manual_expiry: "Expiration (MM/AA)",
    bk_add_card_btn: "Ajouter la carte",
    bk_manual_upload: "Photo de la carte (Optionnel)",
    // Dashboard Specific
    dash_hello: "Bonjour",
    dash_stage_title: "Étape Actuelle",
    dash_day_label: "Jour",
    dash_tasks_left: "tâches restantes",
    dash_completed_pre: "Vous avez complété",
    dash_completed_post: "tâches",
    dash_next_action: "Prochaine Action",
    dash_start_btn: "Commencer",
    dash_alerts: "Alertes",
    dash_quick_actions: "Accès Rapide",
    qa_num: "Numéro Français",
    qa_bank: "Banque",
    qa_navigo: "Navigo",
    qa_caf: "CAF",
    qa_ameli: "Ameli",
    qa_ai: "Assistant IA",
    // Smart Assistant
    sa_title: "Smart Assistant",
    sa_subtitle: "IA Administrative & Sécurité",
    sa_mode_admin: "Analyse Admin",
    sa_mode_admin_desc: "Analyser courriers, emails & documents",
    sa_mode_safety: "Vérification Sécurité",
    sa_mode_safety_desc: "Vérifier SMS, URL ou Emails suspects",
    sa_input_placeholder: "Collez texte, URL ou image...",
    sa_analyze_btn: "Analyser",
    sa_risk_high: "HAUT RISQUE",
    sa_risk_medium: "RISQUE MOYEN",
    sa_risk_low: "SÛR",
    sa_safe_link: "Lien Officiel",
    sa_deadline: "Date limite",
    sa_history: "Analyses récentes",
    sa_section_analysis: "Analyse",
    sa_section_advice: "Conseil d'action",
    sa_btn_another: "Nouvelle analyse",
    sa_demo_btn: "Démo",
    sa_doc_summary: "Résumé du document",
    // Onboarding
    ob_step2_title: "Orange Global Life",
    ob_step2_desc: "Votre compagnon administratif pour vos 90 premiers jours en France.",
    ob_feat_esim: "Numéro Français",
    ob_feat_bank: "Banque & RIB",
    ob_feat_navigo: "Transport",
    ob_feat_caf: "Santé & Logement",
    ob_step3_title: "Vos 90 Premiers Jours",
    ob_day1: "Jour 1",
    ob_day3: "Jours 1-3",
    ob_week1: "Semaine 1",
    ob_week2: "Semaine 2",
    btn_continue: "Continuer",
    btn_start: "Commencer",
    // Profile
    p_identity: "Identité",
    p_name_label: "Nom",
    p_guest: "Utilisateur Invité",
    p_type: "Type d'utilisateur",
    p_student: "Étudiant",
    p_worker: "Travailleur",
    p_visitor: "Visiteur",
    p_prefs: "Préférences",
    p_lang: "Langue",
    p_notifs: "Notifications",
    p_docs: "Mes Documents",
    p_doc_added: "Ajouté Jour 1",
    p_doc_missing: "Manquant",
    p_empty_docs: "Aucun document téléchargé.",
    p_export: "Exporter le dossier administratif",
    p_downloading_alert: "Dossier administratif (ZIP) téléchargé !",
    p_privacy: "Confidentialité & Données",
    p_help: "Centre d'aide",
    p_reset: "Réinitialiser la démo",
    p_phone: "Numéro de téléphone",
    p_userid: "ID Utilisateur",
    p_delete: "Supprimer le compte",
    p_delete_confirm: "Êtes-vous sûr ? Cela effacera toutes les données.",
    // Banking
    bk_identity_title: "Qui êtes-vous ?",
    bk_identity_desc: "Nous avons besoin de votre profil pour recommander la meilleure banque.",
    bk_step1_title: "Documents",
    bk_step1_desc: "Requis pour votre profil :",
    bk_upload_tip: "Classification Auto IA Active",
    bk_upload_pkg: "Analyser mes documents",
    bk_analyzing: "Calcul des scores...",
    bk_stat_compat: "Compatibilité",
    bk_stat_success: "Taux de succès",
    bk_rec_title: "Banques Recommandées",
    bk_rec_online: "Banques en ligne",
    bk_rec_physical: "Agencies",
    bk_open: "Ouvrir le site",
    bk_book: "Prendre rendez-vous",
    bk_call: "Appeler l'agence",
    bk_score: "Score",
    bk_filter_all: "Toutes",
    bk_filter_online: "En ligne",
    bk_filter_physical: "Agences",
    // eSIM
    esim_start: "Commencer l’activation eSIM",
    esim_checking: "Vérification de la compatibilité...",
    esim_compatible: "Votre appareil est compatible avec l’eSIM.",
    esim_incompatible: "Votre appareil ne prend pas en charge l’eSIM.",
    esim_passport_label: "Numéro de passeport",
    esim_activate: "Activer maintenant",
    esim_activating: "Activation du profil...",
    esim_connecting: "Connexion au réseau Orange France...",
    esim_store_opt: "Aller à la boutique Orange la plus proche",
    esim_kiosk_opt: "Récupérer une carte SIM aux bornes automatiques",
    esim_skip: "Passer pour l'instant",
    esim_success: "eSIM activée avec succès",
    esim_success_desc: "Votre numéro français est prêt :",
    esim_continue: "Continuer",
    esim_already_have: "Vous avez déjà une SIM ?",
    esim_track_usage: "Suivre la consommation",
    esim_enter_number: "Entrez votre numéro français",
    esim_plan_usage: "Suivi Conso",
    esim_data_left: "Internet Restant",
    esim_unlimited: "Illimité",
    esim_calls_sms: "Appels & SMS",
    esim_days_left: "Jours Restants",
    esim_balance: "Solde",
    esim_renew: "Renouvellement",
    esim_redownload: "Retélécharger eSIM",
    esim_redownload_available: "Disponible",
    esim_btn_history: "Historique",
    esim_btn_topup: "Recharger",
    esim_btn_plan: "Changer d'offre",
    esim_account_created: "Compte créé pour sauvegarder la progression.",
    // Help Center
    help_title: "Centre d'aide",
    help_official_links: "Ressources Officielles",
    help_faq: "Questions Fréquentes",
    help_safety_title: "Restez vigilant",
    help_safety_desc: "Ne partagez jamais vos mots de passe ou codes bancaires par SMS. Les organismes officiels (CAF, Ameli) ne les demanderont jamais par SMS.",
    splash_loading: "Chargement...",

    // Arrays
    faqs: [
        { q: "Comment obtenir un numéro de sécurité sociale ?", a: "Inscrivez-vous sur etudiant-etranger.ameli.fr dès votre arrivée." },
        { q: "Puis-je ouvrir un compte sans numéro français ?", a: "Certaines banques en ligne (N26, Revolut) le permettent, mais les banques traditionnelles l'exigent." },
        { q: "Qu'est-ce un RIB ?", a: "Relevé d'Identité Bancaire. Ce sont vos coordonnées bancaires pour le salaire et les prélèvements." },
    ],
    help_links: [
        { name: 'CAF (Allocations Familiales)', url: 'https://www.caf.fr', icon: '🏠' },
        { name: 'Ameli (Assurance Maladie)', url: 'https://www.ameli.fr', icon: '❤️' },
        { name: 'Navigo (Transports)', url: 'https://www.iledefrance-mobilites.fr', icon: '🚇' },
        { name: 'Service Public (Admin)', url: 'https://www.service-public.fr', icon: '🇫🇷' },
    ],
    alerts: [
      {
        id: '1',
        type: 'administrative',
        title: 'CAF : Document manquant',
        description: 'Veuillez télécharger votre contrat de location.',
        date: '12 Déc',
        actionLabel: 'Télécharger'
      },
      {
        id: '2',
        type: 'security',
        title: 'Attention : message suspect',
        description: 'SMS suspect détecté. Ne cliquez pas sur les liens.',
        actionLabel: 'Vérifier'
      }
    ],
    mock_ai: {
      administrative: {
        type: 'administrative',
        summary: "La CAF a besoin d'un document manquant (Contrat de location) pour traiter votre demande d'aide au logement.",
        steps: [
          "Scannez votre 'Bail de location' (Contrat de location).",
          "Connectez-vous sur caf.fr > Mon Profil.",
          "Téléchargez le document dans 'Mes Démarches'."
        ],
        deadline: "2024-10-05",
        official_links: [{ name: "CAF - Mon Compte", url: "https://www.caf.fr" }]
      },
      safety: {
        type: 'safety',
        risk_level: 'high',
        explanation: "C'est une tentative de 'Phishing'. L'URL 'ameli-renouvellement.com' est FAUSSE. Le site officiel est ameli.fr.",
        advice: "Ne cliquez PAS sur le lien. Bloquez l'expéditeur. Supprimez le message.",
        official_link: { name: "Ameli Officiel", url: "https://www.ameli.fr" }
      }
    }
  },
  [Language.CN]: {
    welcome: "欢迎来到法国",
    subtitle: "您的 48 小时快速安家指南。",
    start_journey: "开始旅程",
    upload_doc: "上传文件",
    analyzing: "AI 分析中...",
    dashboard: "主页",
    esim: "eSIM",
    banking: "银行开户",
    assistant: "智能助手",
    profile: "个人",
    actions: "行动步骤",
    translate: "翻译",
    docs: {
      passport: "护照",
      visa: "签证",
      address_proof: "地址证明",
      school_certificate: "学生证明",
      work_contract: "工作合同"
    },
    cta: {
      upload_single: "上传文件",
      upload_all: "一次性上传所有文件",
      analyze: "AI 分析并推荐银行",
      reupload: "重新上传"
    },
    identity_labels: {
      student: "学生",
      worker: "工作者",
      visitor: "访客"
    },
    bank_reasons: {
        student_online: "最适合学生：无需收入证明。",
        student_bnp: "校园合作多，网点覆盖广。",
        worker_physical: "适合工资代发和全套保险。",
        worker_lcl: "工作者首选，房贷优惠。",
        visitor_online: "访客开户最快。",
        visitor_physical: "无长居签证较难开户。",
        default: "不错的标准选择。"
    },
    // Banking New Flow
    bk_already_have: "已有银行账户？",
    bk_enter_iban: "输入 IBAN 或 RIB",
    bk_iban_placeholder: "FR76 1234 5678...",
    bk_confirm_iban: "确认添加",
    bk_account_added: "银行账户已添加！",
    bk_add_card_intro: "继续添加银行卡以便管理与支付：",
    bk_add_card_title: "添加银行卡 (NFC/手动)",
    bk_add_nfc: "通过 NFC 添加",
    bk_add_manual: "手动输入",
    bk_nfc_instruction: "将银行卡贴近手机背面",
    bk_nfc_scanning: "正在读取...",
    bk_card_added: "银行卡添加成功",
    bk_my_cards: "我的银行卡",
    bk_manual_card_num: "卡号",
    bk_manual_expiry: "有效期 (MM/YY)",
    bk_add_card_btn: "添加卡片",
    bk_manual_upload: "上传卡片照片 (可选)",
    // Dashboard Specific
    dash_hello: "你好",
    dash_stage_title: "当前阶段",
    dash_day_label: "第",
    dash_tasks_left: "个待办任务",
    dash_completed_pre: "您已完成",
    dash_completed_post: "个任务，剩余",
    dash_next_action: "下一步",
    dash_start_btn: "立即开始",
    dash_alerts: "重要提醒",
    dash_quick_actions: "快捷入口",
    qa_num: "法国号码",
    qa_bank: "银行开户",
    qa_navigo: "交通卡",
    qa_caf: "CAF 房补",
    qa_ameli: "医保 Ameli",
    qa_ai: "AI 助手",
    // Smart Assistant
    sa_title: "智能助手",
    sa_subtitle: "行政与安全 AI",
    sa_mode_admin: "行政文件分析",
    sa_mode_admin_desc: "解读行政信件、邮件或文档",
    sa_mode_safety: "安全反诈检测",
    sa_mode_safety_desc: "检测可疑短信、网址或邮件",
    sa_input_placeholder: "粘贴文本、网址或上传图片...",
    sa_analyze_btn: "开始分析",
    sa_risk_high: "高风险 (诈骗)",
    sa_risk_medium: "中风险",
    sa_risk_low: "安全",
    sa_safe_link: "官方正确链接",
    sa_deadline: "截止日期",
    sa_history: "最近记录",
    sa_section_analysis: "分析结果",
    sa_section_advice: "行动建议",
    sa_btn_another: "分析下一个",
    sa_demo_btn: "演示",
    sa_doc_summary: "文档摘要",
    // Onboarding
    ob_step2_title: "Orange Global Life",
    ob_step2_desc: "帮助您在法国前 90 天顺利安家的行政助手。",
    ob_feat_esim: "法国号码",
    ob_feat_bank: "银行与 RIB",
    ob_feat_navigo: "交通卡",
    ob_feat_caf: "医保与房补",
    ob_step3_title: "您的前 90 天规划",
    ob_day1: "第 1 天",
    ob_day3: "第 1-3 天",
    ob_week1: "第 1 周",
    ob_week2: "第 2 周",
    btn_continue: "继续",
    btn_start: "开始旅程",
    // Profile
    p_identity: "身份信息",
    p_name_label: "姓名",
    p_guest: "访客用户",
    p_type: "用户类型",
    p_student: "学生",
    p_worker: "工作者",
    p_visitor: "访客",
    p_prefs: "偏好设置",
    p_lang: "语言",
    p_notifs: "通知推送",
    p_docs: "我的文件",
    p_doc_added: "已添加 (第1天)",
    p_doc_missing: "缺失",
    p_empty_docs: "暂未上传文件。",
    p_export: "导出行政文件包",
    p_downloading_alert: "行政文件包 (ZIP) 已下载！",
    p_privacy: "隐私与数据",
    p_help: "帮助中心",
    p_reset: "重置演示",
    p_phone: "手机号码",
    p_userid: "用户 ID",
    p_delete: "删除账户",
    p_delete_confirm: "确定要删除吗？这将清除所有数据。",
    // Banking
    bk_identity_title: "您的身份？",
    bk_identity_desc: "我们需要您的身份信息来推荐最合适的银行。",
    bk_step1_title: "准备材料",
    bk_step1_desc: "根据您的身份，需要：",
    bk_upload_tip: "AI 自动分类功能已开启",
    bk_upload_pkg: "AI 分析并推荐银行",
    bk_analyzing: "正在计算匹配度...",
    bk_stat_compat: "匹配度",
    bk_stat_success: "开户成功率",
    bk_rec_title: "推荐银行",
    bk_rec_online: "线上银行 (Online)",
    bk_rec_physical: "实体银行 (Agence)",
    bk_open: "访问官网",
    bk_book: "在线预约",
    bk_call: "拨打电话",
    bk_score: "推荐分",
    bk_filter_all: "全部",
    bk_filter_online: "线上银行",
    bk_filter_physical: "实体银行",
    // eSIM
    esim_start: "开始 eSIM 激活",
    esim_checking: "正在检测设备兼容性...",
    esim_compatible: "您的设备支持 eSIM。",
    esim_incompatible: "您的设备不支持 eSIM。",
    esim_passport_label: "护照号码",
    esim_activate: "立即激活",
    esim_activating: "正在激活配置文件...",
    esim_connecting: "正在连接 Orange France 网络...",
    esim_store_opt: "前往最近的 Orange 门店",
    esim_kiosk_opt: "前往机场自动售卡机",
    esim_skip: "暂时跳过",
    esim_success: "eSIM 激活成功",
    esim_success_desc: "您的法国号码已就绪：",
    esim_continue: "继续",
    esim_already_have: "已有 SIM 卡？",
    esim_track_usage: "追踪使用情况",
    esim_enter_number: "输入您的法国号码",
    esim_plan_usage: "套餐使用情况",
    esim_data_left: "剩余流量",
    esim_unlimited: "不限",
    esim_calls_sms: "通话与短信",
    esim_days_left: "剩余天数",
    esim_balance: "余额",
    esim_renew: "套餐更新",
    esim_redownload: "重新下载 eSIM",
    esim_redownload_available: "可用",
    esim_btn_history: "历史记录",
    esim_btn_topup: "充值",
    esim_btn_plan: "更换套餐",
    esim_account_created: "已为您创建账户以保存进度。",
    // Help Center
    help_title: "帮助中心",
    help_official_links: "官方资源",
    help_faq: "常见问题",
    help_safety_title: "保持警惕",
    help_safety_desc: "切勿通过短信分享密码或银行密码。官方机构（CAF、Ameli）绝不会通过短信索要这些信息。",
    splash_loading: "正在加载您的法国旅程...",

    // Arrays
    faqs: [
        { q: "如何获得社保号？", a: "抵达后立即在 etudiant-etranger.ameli.fr 注册。" },
        { q: "没有法国号码可以开户吗？", a: "部分网上银行（N26, Revolut）允许，但传统银行通常需要。" },
        { q: "什么是 RIB？", a: "Relevé d'Identité Bancaire。它是您的银行账户详情，用于工资发放和自动扣款。" },
    ],
    help_links: [
        { name: 'CAF (家庭补助)', url: 'https://www.caf.fr', icon: '🏠' },
        { name: 'Ameli (医疗保险)', url: 'https://www.ameli.fr', icon: '❤️' },
        { name: 'Navigo (交通卡)', url: 'https://www.iledefrance-mobilites.fr', icon: '🚇' },
        { name: 'Service Public (行政官网)', url: 'https://www.service-public.fr', icon: '🇫🇷' },
    ],
    alerts: [
      {
        id: '1',
        type: 'administrative',
        title: 'CAF：缺失文件',
        description: '请上传您的租房合同。',
        date: '12月12日',
        actionLabel: '上传'
      },
      {
        id: '2',
        type: 'security',
        title: '注意：检测到可疑短信',
        description: '这可能是诈骗短信，请勿点击链接。',
        actionLabel: '检查'
      }
    ],
    mock_ai: {
      administrative: {
        type: 'administrative',
        summary: "CAF 收到您的申请，但缺少一份文件（租赁合同）。",
        steps: [
          "找到您的 'Bail de location'（租赁合同）。",
          "登录 caf.fr > Mon Compte（我的账户）。",
          "在 'Mes Démarches' 中上传文件。"
        ],
        deadline: "2024-10-05",
        official_links: [{ name: "CAF - 我的账户", url: "https://www.caf.fr" }]
      },
      safety: {
        type: 'safety',
        risk_level: 'high',
        explanation: "这是一个常见的‘钓鱼’诈骗。链接 'ameli-renouvellement.com' 是伪造的。官方网站是 ameli.fr。",
        advice: "切勿点击链接。屏蔽发送者并删除短信。",
        official_link: { name: "Ameli 官网", url: "https://www.ameli.fr" }
      }
    }
  },
  [Language.KR]: {
    welcome: "프랑스에 오신 것을 환영합니다",
    subtitle: "48시간 빠른 정착 가이드.",
    start_journey: "여정 시작",
    upload_doc: "문서 업로드",
    analyzing: "AI 분석 중...",
    dashboard: "대시보드",
    esim: "eSIM",
    banking: "은행",
    assistant: "스마트 어시스턴트",
    profile: "프로필",
    actions: "실행 항목",
    translate: "번역",
    docs: {
      passport: "여권",
      visa: "비자",
      address_proof: "거주 증명서",
      school_certificate: "재학 증명서",
      work_contract: "근로 계약서"
    },
    cta: {
      upload_single: "업로드",
      upload_all: "모든 파일 한 번에 업로드",
      analyze: "AI 분석 및 추천",
      reupload: "다시 업로드"
    },
    identity_labels: {
      student: "학생",
      worker: "직장인",
      visitor: "방문자"
    },
    bank_reasons: {
        student_online: "학생에게 최적: 소득 증명 불필요.",
        student_bnp: "강력한 학생 파트너십 및 캠퍼스 접근성.",
        worker_physical: "급여 입금 및 보험에 이상적.",
        worker_lcl: "직장인 및 주택 대출에 좋음.",
        visitor_online: "방문자를 위한 가장 빠른 개설.",
        visitor_physical: "장기 비자 없이 개설 어려움.",
        default: "무난한 표준 옵션."
    },
    // Banking New Flow
    bk_already_have: "이미 은행 계좌가 있나요?",
    bk_enter_iban: "IBAN 또는 RIB 입력",
    bk_iban_placeholder: "FR76 1234 5678...",
    bk_confirm_iban: "계좌 확인",
    bk_account_added: "은행 계좌가 추가되었습니다!",
    bk_add_card_intro: "관리 및 결제를 위해 카드를 계속 추가하세요:",
    bk_add_card_title: "카드 추가 (NFC/수동)",
    bk_add_nfc: "NFC로 추가",
    bk_add_manual: "수동 입력",
    bk_nfc_instruction: "카드를 휴대폰 뒷면에 대세요",
    bk_nfc_scanning: "스캔 중...",
    bk_card_added: "카드가 성공적으로 추가되었습니다",
    bk_my_cards: "내 카드",
    bk_manual_card_num: "카드 번호",
    bk_manual_expiry: "유효기간 (MM/YY)",
    bk_add_card_btn: "카드 추가",
    bk_manual_upload: "카드 사진 업로드 (선택)",
    // Dashboard Specific
    dash_hello: "안녕하세요",
    dash_stage_title: "현재 단계",
    dash_day_label: "일차",
    dash_tasks_left: "개의 남은 작업",
    dash_completed_pre: "완료한 작업:",
    dash_completed_post: "개, 남은 작업:",
    dash_next_action: "다음 작업",
    dash_start_btn: "시작하기",
    dash_alerts: "알림",
    dash_quick_actions: "빠른 실행",
    qa_num: "프랑스 번호",
    qa_bank: "은행",
    qa_navigo: "Navigo",
    qa_caf: "CAF",
    qa_ameli: "Ameli",
    qa_ai: "AI 비서",
    // Smart Assistant
    sa_title: "스마트 어시스턴트",
    sa_subtitle: "행정 및 보안 AI",
    sa_mode_admin: "행정 문서 분석",
    sa_mode_admin_desc: "편지, 이메일 및 문서 분석",
    sa_mode_safety: "보안 및 사기 감지",
    sa_mode_safety_desc: "의심스러운 문자, URL 확인",
    sa_input_placeholder: "텍스트, URL 붙여넣기 또는 이미지 업로드...",
    sa_analyze_btn: "분석 시작",
    sa_risk_high: "고위험 (사기)",
    sa_risk_medium: "중위험",
    sa_risk_low: "안전함",
    sa_safe_link: "공식 안전 링크",
    sa_deadline: "마감일",
    sa_history: "최근 기록",
    sa_section_analysis: "분석 결과",
    sa_section_advice: "조언",
    sa_btn_another: "다른 항목 분석",
    sa_demo_btn: "데모",
    sa_doc_summary: "문서 요약",
    // Onboarding
    ob_step2_title: "Orange Global Life",
    ob_step2_desc: "프랑스 정착 첫 90일을 위한 최고의 행정 도우미.",
    ob_feat_esim: "프랑스 번호",
    ob_feat_bank: "은행 & RIB",
    ob_feat_navigo: "교통",
    ob_feat_caf: "건강 & 주거",
    ob_step3_title: "첫 90일 여정",
    ob_day1: "1일차",
    ob_day3: "1-3일차",
    ob_week1: "1주차",
    ob_week2: "2주차",
    btn_continue: "계속",
    btn_start: "여정 시작",
    // Profile
    p_identity: "신원 정보",
    p_name_label: "이름",
    p_guest: "게스트 사용자",
    p_type: "사용자 유형",
    p_student: "학생",
    p_worker: "직장인",
    p_visitor: "방문자",
    p_prefs: "환경 설정",
    p_lang: "언어",
    p_notifs: "알림",
    p_docs: "내 문서",
    p_doc_added: "추가됨 (1일차)",
    p_doc_missing: "누락됨",
    p_empty_docs: "업로드된 문서가 없습니다.",
    p_export: "행정 문서 패키지 내보내기",
    p_downloading_alert: "행정 문서 패키지(ZIP) 다운로드 완료!",
    p_privacy: "개인정보 & 데이터",
    p_help: "고객 센터",
    p_reset: "데모 초기화",
    p_phone: "휴대폰 번호",
    p_userid: "사용자 ID",
    p_delete: "계정 삭제",
    p_delete_confirm: "정말 삭제하시겠습니까? 모든 데이터가 삭제됩니다.",
    // Banking
    bk_identity_title: "누구신가요?",
    bk_identity_desc: "최적의 은행을 추천하기 위해 프로필이 필요합니다.",
    bk_step1_title: "필수 서류",
    bk_step1_desc: "사용자 유형에 따른 서류:",
    bk_upload_tip: "AI 자동 분류 활성화",
    bk_upload_pkg: "문서 분석 및 추천",
    bk_analyzing: "AI 점수 계산 중...",
    bk_stat_compat: "호환성",
    bk_stat_success: "성공률",
    bk_rec_title: "추천 은행",
    bk_rec_online: "온라인 은행",
    bk_rec_physical: "지점 방문",
    bk_open: "웹사이트 열기",
    bk_book: "방문 예약",
    bk_call: "전화 걸기",
    bk_score: "점수",
    bk_filter_all: "전체",
    bk_filter_online: "온라인",
    bk_filter_physical: "오프라인",
    // eSIM
    esim_start: "eSIM 활성화 시작",
    esim_checking: "기기 호환성 확인 중...",
    esim_compatible: "기기가 eSIM을 지원합니다.",
    esim_incompatible: "기기가 eSIM을 지원하지 않습니다.",
    esim_passport_label: "여권 번호",
    esim_activate: "지금 활성화",
    esim_activating: "프로필 활성화 중...",
    esim_connecting: "Orange France 네트워크 연결 중...",
    esim_store_opt: "가까운 Orange 매장 찾기",
    esim_kiosk_opt: "공항 키오스크에서 수령",
    esim_skip: "건너뛰기",
    esim_success: "eSIM 활성화 완료",
    esim_success_desc: "프랑스 번호가 준비되었습니다:",
    esim_continue: "계속",
    esim_already_have: "이미 SIM이 있으신가요?",
    esim_track_usage: "사용량 조회",
    esim_enter_number: "프랑스 번호를 입력하세요",
    esim_plan_usage: "요금제 사용량",
    esim_data_left: "남은 데이터",
    esim_unlimited: "무제한",
    esim_calls_sms: "통화 & 문자",
    esim_days_left: "남은 기간",
    esim_balance: "잔액",
    esim_renew: "갱신일",
    esim_redownload: "eSIM 다시 다운로드",
    esim_redownload_available: "가능",
    esim_btn_history: "내역",
    esim_btn_topup: "충전",
    esim_btn_plan: "요금제 변경",
    esim_account_created: "진행 상황 저장을 위해 계정이 생성되었습니다.",
    // Help Center
    help_title: "고객 센터",
    help_official_links: "공식 리소스",
    help_faq: "자주 묻는 질문",
    help_safety_title: "안전 유의",
    help_safety_desc: "문자로 비밀번호나 핀 번호를 공유하지 마세요. 공식 기관(CAF, Ameli)은 절대 문자로 이를 요구하지 않습니다.",
    splash_loading: "로딩 중...",

    // Arrays
    faqs: [
        { q: "사회보장번호는 어떻게 받나요?", a: "도착 즉시 etudiant-etranger.ameli.fr에 등록하세요." },
        { q: "프랑스 번호 없이 계좌 개설이 가능한가요?", a: "일부 온라인 은행(N26, Revolut)은 가능하지만, 기존 은행은 필요합니다." },
        { q: "RIB란 무엇인가요?", a: "은행 계좌 증명서입니다. 급여 및 자동 이체에 필요합니다." },
    ],
    help_links: [
        { name: 'CAF (주거 보조금)', url: 'https://www.caf.fr', icon: '🏠' },
        { name: 'Ameli (건강 보험)', url: 'https://www.ameli.fr', icon: '❤️' },
        { name: 'Navigo (교통)', url: 'https://www.iledefrance-mobilites.fr', icon: '🚇' },
        { name: 'Service Public (공공 서비스)', url: 'https://www.service-public.fr', icon: '🇫🇷' },
    ],
    alerts: [
      {
        id: '1',
        type: 'administrative',
        title: 'CAF: 문서 누락',
        description: '임대 계약서를 업로드해주세요.',
        date: '12월 12일',
        actionLabel: '업로드'
      },
      {
        id: '2',
        type: 'security',
        title: '주의: 의심스러운 메시지 감지',
        description: '사기성 문자로 의심됩니다. 링크를 클릭하지 마세요.',
        actionLabel: '확인'
      }
    ],
    mock_ai: {
      administrative: {
        type: 'administrative',
        summary: "CAF는 주거 지원 신청을 처리하기 위해 누락된 문서(임대 계약서)가 필요합니다.",
        steps: [
          "'Bail de location'(임대 계약서)을 스캔하세요.",
          "caf.fr > 내 계정(My Profile)에 로그인하세요.",
          "'Mes Démarches'에서 문서를 업로드하세요."
        ],
        deadline: "2024-10-05",
        official_links: [{ name: "CAF - 내 계정", url: "https://www.caf.fr" }]
      },
      safety: {
        type: 'safety',
        risk_level: 'high',
        explanation: "이것은 흔한 '피싱' 사기 시도입니다. URL 'ameli-renouvellement.com'은 가짜입니다. 공식 사이트는 ameli.fr입니다.",
        advice: "링크를 클릭하지 마세요. 발신자를 차단하고 메시지를 삭제하세요.",
        official_link: { name: "Ameli 공식", url: "https://www.ameli.fr" }
      }
    }
  },
  [Language.JP]: {
    welcome: "フランスへようこそ",
    subtitle: "48時間以内の迅速な定住ガイド。",
    start_journey: "旅を始める",
    upload_doc: "文書アップロード",
    analyzing: "AI分析中...",
    dashboard: "ダッシュボード",
    esim: "eSIM",
    banking: "銀行",
    assistant: "アシスタント",
    profile: "プロフィール",
    actions: "アクション",
    translate: "翻訳",
    docs: {
      passport: "パスポート",
      visa: "ビザ",
      address_proof: "住所証明書",
      school_certificate: "在学証明書",
      work_contract: "雇用契約書"
    },
    cta: {
      upload_single: "アップロード",
      upload_all: "すべてを一括アップロード",
      analyze: "AI 分析・推奨",
      reupload: "再アップロード"
    },
    identity_labels: {
      student: "学生",
      worker: "社会人",
      visitor: "訪問者"
    },
    bank_reasons: {
        student_online: "学生に最適：収入証明不要。",
        student_bnp: "強力な学生パートナーシップとキャンパス内拠点。",
        worker_physical: "給与振込と保険に最適。",
        worker_lcl: "社会人と住宅ローンに最適。",
        visitor_online: "訪問者にとって最も早い口座開設。",
        visitor_physical: "長期ビザなしでは開設が難しい。",
        default: "優れた標準オプション。"
    },
    // Banking New Flow
    bk_already_have: "すでに銀行口座をお持ちですか？",
    bk_enter_iban: "IBANまたはRIBを入力",
    bk_iban_placeholder: "FR76 1234 5678...",
    bk_confirm_iban: "口座を確認",
    bk_account_added: "銀行口座が追加されました！",
    bk_add_card_intro: "管理と支払いのためにカードを追加し続けてください：",
    bk_add_card_title: "カードを追加 (NFC/手動)",
    bk_add_nfc: "NFC経由で追加",
    bk_add_manual: "手動入力",
    bk_nfc_instruction: "カードを携帯電話の背面にかざしてください",
    bk_nfc_scanning: "スキャン中...",
    bk_card_added: "カードが正常に追加されました",
    bk_my_cards: "マイカード",
    bk_manual_card_num: "カード番号",
    bk_manual_expiry: "有効期限 (MM/YY)",
    bk_add_card_btn: "カードを追加",
    bk_manual_upload: "カード写真アップロード (任意)",
    // Dashboard Specific
    dash_hello: "こんにちは",
    dash_stage_title: "現在のステージ",
    dash_day_label: "日目",
    dash_tasks_left: "個のタスクが残っています",
    dash_completed_pre: "完了:",
    dash_completed_post: "タスク、残り:",
    dash_next_action: "次のアクション",
    dash_start_btn: "開始",
    dash_alerts: "アラート",
    dash_quick_actions: "クイックアクション",
    qa_num: "フランスの番号",
    qa_bank: "銀行口座",
    qa_navigo: "Navigo",
    qa_caf: "CAF",
    qa_ameli: "Ameli",
    qa_ai: "AI アシスタント",
    // Smart Assistant
    sa_title: "スマートアシスタント",
    sa_subtitle: "行政 & セキュリティAI",
    sa_mode_admin: "行政文書分析",
    sa_mode_admin_desc: "手紙、メール、文書を分析",
    sa_mode_safety: "セキュリティチェック",
    sa_mode_safety_desc: "不審なSMS、URLを確認",
    sa_input_placeholder: "テキスト、URL、または画像を貼り付け...",
    sa_analyze_btn: "分析開始",
    sa_risk_high: "高リスク (詐欺)",
    sa_risk_medium: "中リスク",
    sa_risk_low: "安全",
    sa_safe_link: "公式リンク",
    sa_deadline: "締切日",
    sa_history: "最近の分析",
    sa_section_analysis: "分析結果",
    sa_section_advice: "アドバイス",
    sa_btn_another: "他を分析",
    sa_demo_btn: "デモ",
    sa_doc_summary: "文書の概要",
    // Onboarding
    ob_step2_title: "Orange Global Life",
    ob_step2_desc: "フランスでの最初の90日間をサポートする究極の管理アシスタント。",
    ob_feat_esim: "フランスの番号",
    ob_feat_bank: "銀行 & RIB",
    ob_feat_navigo: "交通機関",
    ob_feat_caf: "健康 & 住宅",
    ob_step3_title: "最初の90日間",
    ob_day1: "1日目",
    ob_day3: "1-3日目",
    ob_week1: "1週目",
    ob_week2: "2週目",
    btn_continue: "次へ",
    btn_start: "旅を始める",
    // Profile
    p_identity: "本人情報",
    p_name_label: "氏名",
    p_guest: "ゲストユーザー",
    p_type: "ユーザータイプ",
    p_student: "学生",
    p_worker: "社会人",
    p_visitor: "訪問者",
    p_prefs: "設定",
    p_lang: "言語",
    p_notifs: "通知",
    p_docs: "マイドキュメント",
    p_doc_added: "1日目に追加",
    p_doc_missing: "未提出",
    p_empty_docs: "書類はまだアップロードされていません。",
    p_export: "行政書類パッケージをエクスポート",
    p_downloading_alert: "行政書類パッケージ（ZIP）をダウンロードしました！",
    p_privacy: "プライバシー & データ",
    p_help: "ヘルプセンター",
    p_reset: "デモをリセット",
    p_phone: "電話番号",
    p_userid: "ユーザーID",
    p_delete: "アカウント削除",
    p_delete_confirm: "本当によろしいですか？すべてのデータが消去されます。",
    // Banking
    bk_identity_title: "あなたは？",
    bk_identity_desc: "最適な銀行を推奨するためにプロフィールが必要です。",
    bk_step1_title: "必要書類",
    bk_step1_desc: "プロフィールに基づく要件:",
    bk_upload_tip: "AI自動分類が有効です",
    bk_upload_pkg: "書類を分析して推奨",
    bk_analyzing: "AIスコアリング中...",
    bk_stat_compat: "適合性",
    bk_stat_success: "成功率",
    bk_rec_title: "おすすめの銀行",
    bk_rec_online: "オンライン銀行",
    bk_rec_physical: "実店舗",
    bk_open: "公式サイト",
    bk_book: "予約する",
    bk_call: "電話する",
    bk_score: "スコア",
    bk_filter_all: "すべて",
    bk_filter_online: "オンライン",
    bk_filter_physical: "実店舗",
    // eSIM
    esim_start: "eSIMのアクティベーションを開始",
    esim_checking: "デバイスの互換性を確認中...",
    esim_compatible: "お使いのデバイスはeSIMに対応しています。",
    esim_incompatible: "お使いのデバイスはeSIMに対応していません。",
    esim_passport_label: "パスポート番号",
    esim_activate: "今すぐ有効化",
    esim_activating: "プロファイルを有効化中...",
    esim_connecting: "Orange Franceネットワークに接続中...",
    esim_store_opt: "最寄りのOrangeストアへ",
    esim_kiosk_opt: "空港のキオスクでSIMを受け取る",
    esim_skip: "スキップ",
    esim_success: "eSIMの有効化に成功しました",
    esim_success_desc: "フランスの電話番号が使用可能です：",
    esim_continue: "次へ",
    esim_already_have: "すでにSIMをお持ちですか？",
    esim_track_usage: "使用状況を確認",
    esim_enter_number: "フランスの電話番号を入力",
    esim_plan_usage: "プランの使用状況",
    esim_data_left: "残データ",
    esim_unlimited: "無制限",
    esim_calls_sms: "通話 & SMS",
    esim_days_left: "残り日数",
    esim_balance: "残高",
    esim_renew: "更新日",
    esim_redownload: "eSIMの再ダウンロード",
    esim_redownload_available: "利用可能",
    esim_btn_history: "履歴",
    esim_btn_topup: "チャージ",
    esim_btn_plan: "プラン変更",
    esim_account_created: "進捗を保存するためにアカウントが作成されました。",
    // Help Center
    help_title: "ヘルプセンター",
    help_official_links: "公式リソース",
    help_faq: "よくある質問",
    help_safety_title: "安全のために",
    help_safety_desc: "SMSでパスワードや暗証番号を共有しないでください。公的機関（CAF、Ameli）がSMSでこれらを求めることはありません。",
    splash_loading: "読み込み中...",

    // Arrays
    faqs: [
        { q: "社会保障番号はどうやって取得しますか？", a: "到着後すぐに etudiant-etranger.ameli.fr で登録してください。" },
        { q: "フランスの番号なしで口座開設できますか？", a: "一部のオンライン銀行（N26, Revolut）では可能ですが、従来の銀行では必要です。" },
        { q: "RIBとは何ですか？", a: "Relevé d'Identité Bancaire。給与振込や口座引き落としに必要な銀行口座情報です。" },
    ],
    help_links: [
        { name: 'CAF (家族手当)', url: 'https://www.caf.fr', icon: '🏠' },
        { name: 'Ameli (健康保険)', url: 'https://www.ameli.fr', icon: '❤️' },
        { name: 'Navigo (交通機関)', url: 'https://www.iledefrance-mobilites.fr', icon: '🚇' },
        { name: 'Service Public (行政)', url: 'https://www.service-public.fr', icon: '🇫🇷' },
    ],
    alerts: [
      {
        id: '1',
        type: 'administrative',
        title: 'CAF：書類不足',
        description: '賃貸契約書をアップロードしてください。',
        date: '12月12日',
        actionLabel: 'アップロード'
      },
      {
        id: '2',
        type: 'security',
        title: '注意：不審なメッセージを検出',
        description: '詐欺SMSの可能性があります。リンクをクリックしないでください。',
        actionLabel: '確認'
      }
    ],
    mock_ai: {
      administrative: {
        type: 'administrative',
        summary: "CAFは住宅支援の申請を進めるために、不足している書類（賃貸契約書）を必要としています。",
        steps: [
          "'Bail de location'（賃貸契約書）をスキャンしてください。",
          "caf.fr > My Profile（マイアカウント）にログインしてください。",
          "'Mes Démarches'（手続き）で書類をアップロードしてください。"
        ],
        deadline: "2024-10-05",
        official_links: [{ name: "CAF - マイアカウント", url: "https://www.caf.fr" }]
      },
      safety: {
        type: 'safety',
        risk_level: 'high',
        explanation: "これは一般的な「フィッシング」詐欺の試みです。URL 'ameli-renouvellement.com' は偽物です。公式サイトは ameli.fr です。",
        advice: "リンクをクリックしないでください。送信者をブロックし、メッセージを削除してください。",
        official_link: { name: "Ameli 公式", url: "https://www.ameli.fr" }
      }
    }
  }
};